### ISSUE TITLE
Could FAQ scripts load only on a page they are needed?

### ISSUE THREAD

**Issue by webprom** [vishalck/arconix-faq#46]
HI!

Usually sites have only 1 page for a FAQ, at least me :) Could you please add such functionality?

**Comment by j-gardner** [comment]
Hi,

Which script are you referring to?

**Comment by webprom** [comment]
jQury ui, //ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css
http://www.fix-css.com/2016/04/arconix-faq-plugin-customization-for-better-speed-with-autoptimize/

**Comment by j-gardner** [comment]
http://beerpla.net/2010/01/13/wordpress-plugin-development-how-to-include-css-and-javascript-conditionally-and-only-when-needed-by-the-posts/

**Comment by webprom** [comment]
yes, some plugins already have this option, to load only on pages needed. hope you'll make it.thanks.

**Comment by j-gardner** [comment]
Sorry, that was a reference note to myself for when I work on this enhancement.
