### ISSUE TITLE
Remove FAQ's when deleting plugin

### ISSUE THREAD

**Issue by j-gardner** [vishalck/arconix-faq#5]
Add an uninstall.php file and have it remove all FAQ items from the posts DB when deleting the plugin

**Comment by mundschenk-at** [comment]
Please only do this if core ever implements https://core.trac.wordpress.org/ticket/20578. Deleting valuable content data should not happen without explicit user approval.

**Comment by mundschenk-at** [comment]
I would urge you to reconsider this. Deleting content during uninstall risks accidental deletion when people are debugging their installations (Ipstenu described this succinctly in the linked core ticket).
