### ISSUE TITLE
Do not delete user content on uninstall

### ISSUE THREAD

**Issue by mundschenk-at** [vishalck/arconix-faq#77]
Please revert  #67.

Deleting valuable user content (FAQ posts) on uninstall is IMHO not acceptable. During debugging you might have to delete a plugin via the GUI. Wiping out all FAQs in that situation is really bad pratice. A much better solution would be a "Delete all data" function in the settings page (with appropriate protection by a secondary "Are you really sure?" confirmation dialog). 

I don't know if there are any options set by the plugin (there probably are), deleting those on uinstall would be fine. Just not the custom posts themselves.

**Comment by bhagyashri12345** [comment]
Hey @mundschenk-at,

We have not yet implemented 'Delete all Data' feature yet. 

Thank you for the suggestion, while implementing we will add an option if you want to keep data or delete it.

Thank you.

**Comment by mundschenk-at** [comment]
@bhagyashri12345 I meant #63. Hadn't noticed you had already reverted that. :-)
