### ISSUE TITLE
After click on "No Thanks" button then notice is not remove

### ISSUE THREAD

**Issue by apeksha10** [vishalck/arconix-faq#86]
After click on "NO Thanks" button, the notice should be dismissed

see the video : https://www.screencast.com/t/ikvD7znKRW

**Comment by bhavik-kiri** [comment]
I've taken git hub copy, and I clicked on No thanks. After clicking, it does not show me the notice again.

I'm not able to replicate the issue.

**Comment by apeksha10** [comment]
This issue replicated when WooCommerce plugin is activated. hence I closed this issue
